package exec;

import testng.TestEventsListener;
import org.testng.TestListenerAdapter;
import org.testng.TestNG;
import org.testng.xml.XmlPackage;
import org.testng.xml.XmlSuite;
import org.testng.xml.XmlTest;

import java.io.File;
import java.io.FileWriter;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.List;

import static conf.Configuration.*;

public class TestLauncher {
    public static void main(String[] args) {
        List<XmlPackage> packages = new LinkedList<>();
        packages.add(new XmlPackage("tests.*"));
        runTests(packages, "BaseSuite");
    }

    private static void runTests(List<XmlPackage> packages, String suiteName) {
        XmlSuite suite = new XmlSuite();
        suite.setName(suiteName);
        suite.setParallel(XmlSuite.ParallelMode.METHODS);
        suite.setThreadCount(TESTING_THREADS);

        XmlTest test = new XmlTest(suite);
        test.setName("Tests");
        test.setXmlPackages(packages);
        if (INCLUDED_GROUPS.length > 0 && !INCLUDED_GROUPS[0].isEmpty())
            test.setIncludedGroups(Arrays.asList(INCLUDED_GROUPS));
        if (EXCLUDED_GROUPS.length > 0 && !EXCLUDED_GROUPS[0].isEmpty())
            test.setExcludedGroups(Arrays.asList(EXCLUDED_GROUPS));

        List<XmlSuite> suites = new LinkedList<>();
        suites.add(suite);


        new File("TestNG_debug.xml").delete();
        String xml = suite.toXml().replace("<!DOCTYPE",
                "<!-- Autogenerated TestNG Suite by class exec.TestLauncher -->\n<!DOCTYPE");
        writeTextToFile("TestNG_debug.xml", xml);

        TestNG tng = new TestNG();
        tng.setXmlSuites(suites);
        tng.setUseDefaultListeners(false);
        TestListenerAdapter tla = new TestListenerAdapter();
        tng.addListener(tla);
        tng.addListener(new TestEventsListener());
        tng.run();
    }

    public static void writeTextToFile(String filePath, String text) {
        if (new File(filePath).exists()) return;
        if (filePath.contains("/")) checkAndFixFoldersPath(filePath.substring(0, filePath.lastIndexOf("/")));
        try (FileWriter fileWriter = new FileWriter(filePath)) {
            fileWriter.write(text);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void checkAndFixFoldersPath(String unixFormatPath) {
        String[] pathTree = unixFormatPath.replace("./", "").split("/");
        String currentLevel = "./";
        for (String s : pathTree) {
            if (s.isEmpty()) continue;
            currentLevel += s + "/";
            new File(currentLevel).mkdir();
        }
    }
}